### PR TITLE
Preserve data add to console app

### PR DESCRIPTION
**Pull request by HENRYKC24**
## In this pull request, I did the following:
1. I preserved the game data by writing it to file
2. I added an interractive console feature to allow users to add a game
3. I added the name property to the game class as per necessity

### CODE REVIEW

**Review by see-why — CHANGES_REQUESTED** [review]
Great job so far @HENRYKC24 ,

I noticed a minor issue though, one I would like you to look at, I got the error in the screen shot below while trying to create a game.

Error

Kindly check it out.

😅

**Comment by HENRYKC24** [comment]
Hi @see-why, I have made some changes to the branch in an attempt to fix the bug. You can re-review now, please.

**Comment by HENRYKC24** [comment]
@mmsesay, you can also re-review if you have the time, please:pray:

**Review by see-why — APPROVED** [review]
Hi @HENRYKC24,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by HENRYKC24** [comment]
Thank you, @see-why:pray: I will proceed to merge the branch as you directed.

**Pull request merged**
